### ISSUE TITLE
Please update the action with ansible-lint 6.9.0 or later

### ISSUE THREAD

**Issue by hulkk** [ansible/ansible-lint-action#140]
The action has been broken since version 6.5.2 up until latest (6.8.2) version. 

Version 6.3.0 of this action is the last one working. Issues can be reproduced locally when using similar version (e.g. 6.8.2). Version 6.9.0 seems to work when run locally.

**Comment by hemberger** [comment]
It would be especially nice if `ansible-lint` releases could automatically trigger `ansible-lint-action` releases so that local and CI environments could stay in sync, but I'm assuming that's not possible because first the `creator-ee` image has to be updated and released.

I'd be happy to help with trivial updates to this repository, if that would be useful to the maintainers (though maybe that's not an option for people outside the ansible org).

**Comment by ssbarnea** [comment]
Done https://github.com/ansible/ansible-lint-action/releases
