### ISSUE TITLE
Image on hub.docker.com

### ISSUE THREAD

**Issue by darkdragon-001** [ansible/ansible-lint-action#67]
Please provide an official container image on Docker Hub. This should increase speed in the Github CI and allow people on Gitlab to use it as well.

**Comment by ssbarnea** [comment]
I am inclined to refuse this due to complexities involved but if someone would propose a github pipeline that we can run on schedule that can sync containers from `quay.io` to `docker.io` and `ghcr.io` registries, I would likely approve it.

I can see the reason, but I just want to avoid including this in normal release pipeline, as any additional external service is likely to cause random outages. Still, a schedule that runs every hour would not hurt anyone.

**Comment by misilot** [comment]
Here is an example GitHub CI Workflow that pushes to GitHub https://github.com/DSpace/DSpace/blob/main/.github/workflows/docker.yml#L92-L156

**Comment by tigattack** [comment]
[akhilerm/tag-push-action](https://github.com/akhilerm/tag-push-action) does pretty much exactly what you want (i.e. pull, re-tag, push).  
There's also [Sinker](https://github.com/plexsystems/sinker), a CLI tool to sync images between repositories.
